---
title: OmniBins

exclude: ['/Gemfile', '/Makefile', '/README.md', '/NOTICE.md', 'LICENSE']

permalink: pretty

collections:
  omnibins:
    output: true

defaults:
  - scope:
      path: '_omnibins'
    values:
      layout: 'bin'
